from __future__ import annotations

import csv
import io
import math
import uuid
import zipfile
from datetime import UTC, date, datetime
from typing import Any
from xml.sax.saxutils import escape as xml_escape

from fastapi import HTTPException, status
from sqlalchemy import String, cast, func, or_, select
from sqlalchemy.orm import Session

from app.models.enums import (
    ApprovalStatus,
    AuditEventType,
    AuditSeverity,
    FulfillmentStatus,
    InventoryStatus,
    ReportCategory,
    ReportFormat,
    ReportStatus,
    RequestPriority,
    RequestStatus,
)
from app.models.inventory import InventoryItem
from app.models.operations import Approval, FulfillmentOrder, OperationalRequest
from app.models.reporting import Report
from app.models.user import User
from app.services.audit_service import record_audit_event
from app.services.serializers import report_to_frontend


def _parse_date(value: str) -> date:
    return date.fromisoformat(value)


def _format_bytes(size: int) -> str:
    if size < 1024:
        return f"{size} B"
    if size < 1024 * 1024:
        return f"{round(size / 1024, 1)} KB"
    return f"{round(size / (1024 * 1024), 1)} MB"


def _metric_rows(db: Session, report: Report) -> list[tuple[str, str]]:
    total_inventory = db.scalar(select(func.coalesce(func.sum(InventoryItem.quantity_on_hand), 0))) or 0
    total_skus = db.scalar(select(func.count()).select_from(InventoryItem)) or 0
    low_stock = db.scalar(
        select(func.count()).select_from(InventoryItem).where(InventoryItem.status.in_([InventoryStatus.LOW, InventoryStatus.CRITICAL]))
    ) or 0
    pending_requests = db.scalar(
        select(func.count()).select_from(OperationalRequest).where(OperationalRequest.status == RequestStatus.PENDING)
    ) or 0
    critical_requests = db.scalar(
        select(func.count())
        .select_from(OperationalRequest)
        .where(OperationalRequest.priority == RequestPriority.CRITICAL, OperationalRequest.status == RequestStatus.PENDING)
    ) or 0
    pending_approvals = db.scalar(
        select(func.count()).select_from(Approval).where(Approval.status == ApprovalStatus.PENDING)
    ) or 0
    delivered = db.scalar(
        select(func.count()).select_from(FulfillmentOrder).where(FulfillmentOrder.status == FulfillmentStatus.DELIVERED)
    ) or 0
    fulfillment_total = db.scalar(select(func.count()).select_from(FulfillmentOrder)) or 0
    fulfillment_completion = round((delivered / fulfillment_total) * 100) if fulfillment_total else 0
    avg_confidence = db.scalar(select(func.avg(OperationalRequest.ai_confidence))) or 0
    return [
        ("Report ID", report.external_id or str(report.id)),
        ("Title", report.title),
        ("Category", report.category.value),
        ("Format", report.format.value),
        ("Generated By", report.generated_by_name),
        ("Date From", report.date_from.isoformat()),
        ("Date To", report.date_to.isoformat()),
        ("Generated At", report.generated_at.isoformat() if report.generated_at else ""),
        ("Total Inventory Units", str(int(total_inventory))),
        ("Managed SKUs", str(int(total_skus))),
        ("Low Or Critical SKUs", str(int(low_stock))),
        ("Pending Requests", str(int(pending_requests))),
        ("Critical Pending Requests", str(int(critical_requests))),
        ("Pending Approvals", str(int(pending_approvals))),
        ("Fulfillment Orders", str(int(fulfillment_total))),
        ("Delivered Orders", str(int(delivered))),
        ("Fulfillment Completion Percent", str(fulfillment_completion)),
        ("Average AI Confidence Percent", str(round(float(avg_confidence)))),
    ]


def list_reports(db: Session) -> list[dict[str, Any]]:
    reports = db.scalars(select(Report).order_by(Report.generated_at.desc().nullslast(), Report.created_at.desc())).all()
    return [report_to_frontend(report) for report in reports]


def get_report(db: Session, report_id: str) -> Report:
    report = db.scalar(select(Report).where(or_(Report.external_id == report_id, cast(Report.id, String) == report_id)))
    if report is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Report not found.")
    return report


def create_report(db: Session, payload: dict[str, Any], actor: User, ip_address: str | None = None) -> Report:
    category = ReportCategory(payload["category"])
    report_format = ReportFormat(payload["format"])
    date_range = payload.get("dateRange") or {}
    report = Report(
        id=uuid.uuid4(),
        external_id=f"rep-{uuid.uuid4().hex[:12]}",
        title=str(payload["title"]).strip(),
        description=f"Generated {category.value} export for date window {date_range.get('from')} to {date_range.get('to')}.",
        category=category,
        status=ReportStatus.GENERATED,
        format=report_format,
        generated_by_user_id=actor.id,
        generated_by_name=actor.display_name,
        generated_at=datetime.now(UTC),
        date_from=_parse_date(date_range["from"]),
        date_to=_parse_date(date_range["to"]),
    )
    db.add(report)
    db.flush()
    content, _, _ = build_report_file(db, report)
    report.file_size = _format_bytes(len(content))
    report.pages = max(1, math.ceil(len(build_report_text(db, report).splitlines()) / 45)) if report_format == ReportFormat.PDF else None
    record_audit_event(
        db,
        event_code="REPORT_GENERATED",
        event_type=AuditEventType.REPORT,
        action="report.generated",
        actor=actor,
        resource_type="Report",
        resource_id=report.external_id or str(report.id),
        description=f"Generated {category.value} report {report.title} in {report_format.value} format.",
        severity=AuditSeverity.INFO,
        metadata={"category": category.value, "format": report_format.value, "fileSize": report.file_size},
        ip_address=ip_address,
    )
    return report


def build_report_text(db: Session, report: Report) -> str:
    lines = [
        "NEXUS ENTERPRISE OPERATIONAL DOSSIER",
        "=" * 45,
        f"Title: {report.title}",
        f"Category: {report.category.value}",
        f"Format: {report.format.value}",
        f"Generated By: {report.generated_by_name}",
        f"Date Range: {report.date_from.isoformat()} to {report.date_to.isoformat()}",
        f"Generated At: {report.generated_at.isoformat() if report.generated_at else ''}",
        "",
        "Database-backed metrics",
        "-" * 45,
    ]
    lines.extend(f"{label}: {value}" for label, value in _metric_rows(db, report)[8:])
    return "\n".join(lines)


def _csv_bytes(db: Session, report: Report) -> bytes:
    stream = io.StringIO()
    writer = csv.writer(stream)
    writer.writerow(["metric", "value"])
    writer.writerows(_metric_rows(db, report))
    return stream.getvalue().encode("utf-8")


def _pdf_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")


def _pdf_bytes(text: str) -> bytes:
    lines = text.splitlines()[:58]
    commands = ["BT", "/F1 10 Tf", "50 780 Td", "14 TL"]
    for line in lines:
        commands.append(f"({_pdf_escape(line[:105])}) Tj")
        commands.append("T*")
    commands.append("ET")
    stream = "\n".join(commands).encode("utf-8")
    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
        b"<< /Length " + str(len(stream)).encode("ascii") + b" >>\nstream\n" + stream + b"\nendstream",
    ]
    output = io.BytesIO()
    output.write(b"%PDF-1.4\n")
    offsets = [0]
    for index, obj in enumerate(objects, start=1):
        offsets.append(output.tell())
        output.write(f"{index} 0 obj\n".encode("ascii"))
        output.write(obj)
        output.write(b"\nendobj\n")
    xref_offset = output.tell()
    output.write(f"xref\n0 {len(objects) + 1}\n".encode("ascii"))
    output.write(b"0000000000 65535 f \n")
    for offset in offsets[1:]:
        output.write(f"{offset:010d} 00000 n \n".encode("ascii"))
    output.write(
        f"trailer << /Size {len(objects) + 1} /Root 1 0 R >>\nstartxref\n{xref_offset}\n%%EOF\n".encode("ascii")
    )
    return output.getvalue()


def _xlsx_bytes(db: Session, report: Report) -> bytes:
    rows = [["Metric", "Value"], *[[label, value] for label, value in _metric_rows(db, report)]]
    sheet_rows = []
    for row_index, row in enumerate(rows, start=1):
        cells = []
        for col_index, value in enumerate(row):
            col_name = chr(ord("A") + col_index)
            cells.append(
                f'<c r="{col_name}{row_index}" t="inlineStr"><is><t>{xml_escape(str(value))}</t></is></c>'
            )
        sheet_rows.append(f'<row r="{row_index}">{"".join(cells)}</row>')
    sheet = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">'
        f'<sheetData>{"".join(sheet_rows)}</sheetData></worksheet>'
    )
    workbook = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" '
        'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">'
        '<sheets><sheet name="NEXUS Report" sheetId="1" r:id="rId1"/></sheets></workbook>'
    )
    content_types = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
        '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
        '<Default Extension="xml" ContentType="application/xml"/>'
        '<Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>'
        '<Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>'
        '</Types>'
    )
    root_rels = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
        '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>'
        '</Relationships>'
    )
    workbook_rels = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
        '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/>'
        '</Relationships>'
    )
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("[Content_Types].xml", content_types)
        archive.writestr("_rels/.rels", root_rels)
        archive.writestr("xl/workbook.xml", workbook)
        archive.writestr("xl/_rels/workbook.xml.rels", workbook_rels)
        archive.writestr("xl/worksheets/sheet1.xml", sheet)
    return buffer.getvalue()


def build_report_file(db: Session, report: Report) -> tuple[bytes, str, str]:
    if report.format == ReportFormat.CSV:
        return _csv_bytes(db, report), "text/csv", "csv"
    if report.format == ReportFormat.XLSX:
        return (
            _xlsx_bytes(db, report),
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            "xlsx",
        )
    return _pdf_bytes(build_report_text(db, report)), "application/pdf", "pdf"
